### ISSUE TITLE
As a system, I want to have diagrams that visually explain how I function, so that I can easily communicate my structure and behaviour.

### ISSUE THREAD

**Issue by capper0074** [Datamatiker2022-Team13/Riptos#14]
### Tasks
- [x] #18 
- [x] #19 
- [x] #43 
- [x] #16 
- [x] #47 
- [ ] #17 
- [x] #15 

### Acceptance criteria
- [ ] All diagrams adhere to their own respective "quality criteria".
- [ ] All diagrams represent the incrementally developed system developed.
- [ ] All diagrams are 🧈-ful! 🦋 ✨

**Comment by jonwangholm** [comment]
SD mangler. Arbejder på SD næste sprint.
