### ISSUE TITLE
As a system, I want to encrypt my sensitive data, so that I can control who can access sensitive data.

### ISSUE THREAD

**Issue by capper0074** [Datamatiker2022-Team13/Riptos#20]
### Tasks
- [x] #13 
- [x] #22 
- [x] #54
- [x] #55
- [x] #35 

### Acceptance criteria
- [x] All types of sensitive data (login information, messages, HR cases and meetings) are encrypted.
- [ ] The method used for encryption is suitably strong.

### System DOC
- [ ] Check DCD
- [ ] Check Object model
- [ ] Check Domænemodel
- [ ] Update Use Case
