### ISSUE TITLE
As a non-HR employee, I would like to send inquiries to my HR representative, so I can contact him/her.

### ISSUE THREAD

**Issue by KasperNissen1997** [Datamatiker2022-Team13/Riptos#3]
### Tasks
- [x] #61
- [x] #62
- [x] #63
- [x] #64

### Acceptance criteria
- [x] The sender and the receiver of an inquiry are the only people who can see and access the inquiry.
- [x] Inquiries contain a subject,
- [ ] Inquiries contain a chat-like conversation field.

### System DOC
- [ ] Check DCD
- [ ] Check Object model
- [ ] Check Domænemodel
- [ ] Update Use Case
