### ISSUE TITLE
As an employee, I would like to see my scheduled meetings in a calendar view, so that I can easily see when my meetings are scheduled for.

### ISSUE THREAD

**Issue by Stokn9x** [Datamatiker2022-Team13/Riptos#44]
### Tasks
- [ ] #49
- [ ] #50
- [ ] #51

### Acceptance criteria
- [ ] All employees can access their own personal calendar.
- [ ] The calendar only shows HR-related meetings.
- [ ] The calendar is intuitive.

### System DOC
- [ ] Check DCD
- [ ] Check Object model
- [ ] Check Domænemodel
- [ ] Update Use Case
