### ISSUE TITLE
As a system, I would like a graphical user interface, so that I am intuitively interactable.

### ISSUE THREAD

**Issue by KasperNissen1997** [Datamatiker2022-Team13/Riptos#72]
### Tasks
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78

### Acceptance criteria
- [x] The UIs are logical.
- [ ] The UIs adhere to CRAP.
- [x] The UIs are easy to navigate.
- [ ] The UIs satisfy the 10 heuristics for usability, to a satisfactory extent.

### System DOC
- [ ] Check DCD
- [ ] Check Object model
- [ ] Check Domænemodel
- [ ] Update Use Case

**Comment by KasperNissen1997** [comment]
Closed as of now.
