### ISSUE TITLE
As a system, I want to satisfy all the CRUD criteria across all my data, so that I can properly manage my data.

### ISSUE THREAD

**Issue by capper0074** [Datamatiker2022-Team13/Riptos#8]
### Tasks
- [x] #28 
- [x] #29 
- [x] #57
- [x] #31 

### Acceptance criteria
- [x] All necessary CRUD specifications per datatype are implemented.

### System DOC
- [x] Check DCD
- [ ] Check Object model
- [ ] Check Domænemodel
- [ ] Update Use Case

**Comment by KasperNissen1997** [comment]
Me and @jonwangholm started working on #57, #31.

**Comment by KasperNissen1997** [comment]
CRUD is still missing for Meeting.

**Comment by KasperNissen1997** [comment]
@Mathiaslk3 @mathiaslk and I approved this!
