### ISSUE TITLE
As a user, I would like to be able to send a message in an inquiry, so that I can chat.

### ISSUE THREAD

**Issue by KasperNissen1997** [Datamatiker2022-Team13/Riptos#87]
# Tasks 📋
Analysis tasks should be completed before work begins on the implementation tasks.
## Analysis 🔬
- [x] #88
- [x] #89
- [x] #90
- [x] #91
- [x] #92

## Implementation 💻
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97

# Acceptance Criteria ✨
- [x] The repositories function the same as before.
- [x] Only the employees that are part of the inquiry can respond.
- [x] Replies sent in an inquiry are only part of that inquiries conversation, and do not show up in other inquiries' conversations.
